spring:
  data:
    mongodb:
      database: products_db
      host: localhost
      port: 27017

#spring:
#  data:
#    cassandra:
#      contact-points: localhost
#      port: 9042
#      keyspace-name: simple_crud
#      #username: cassandra
#      #password: cassandra
#      #schema-act: create_if_not_exists

# TODO : Update cassandra mvn dependency, repository and entities classes accordingly (Replace Cassandra with mongo)

server:
  port: 9292